### ISSUE TITLE
"Plot all" feature needs to be redesign

### ISSUE THREAD

**Issue by khchenTW** [tu-dortmund-ls12-rt/SSSEvaluation#6]
- Plot all does not work on its own -> If we chose only "plot all" it
should print the data from previous runs, i.e., the ones already created.
There is no reason why we should also replot all individual data.

We should have two cases, either you just want to compare different method with the same setting over different utilization, or plot all methods with multiple figures (but only one changing parameter).

**Comment by kuanhsunchen** [comment]
I think this issue is done.

**Comment by kuanhsunchen** [comment]
I think this issue is done

**Comment by kuanhsunchen** [comment]
@TaiJungChang1105 Could you help me check again for this? I think I fix this already.
