### ISSUE TITLE
Multiple plots do not work as expected

### ISSUE THREAD

**Issue by khchenTW** [tu-dortmund-ls12-rt/SSSEvaluation#7]
- Multiple Plots does not work as expected. It plots 3 figures but only
for one method, i.e., only "plot data" is working correctly here.
Furthermore, it only works if "plot data" is chosen (see point above).

Even you have finished the experiments for different methods beforehand, the multiple figure, e.g., EFFSSTS[2][0.01-0.1][[5, 10, 15]], still only show one method.

**Comment by kuanhsunchen** [comment]
This is done

**Comment by khchenTW** [comment]
... no the label of X-axis is wrong somehow
